<?php

namespace AppBundle\Repository;

/**
 * EventOccurrenceCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventOccurrenceCostRepository extends \Doctrine\ORM\EntityRepository
{
}
