<?php

namespace AppBundle\Repository;

/**
 * EventOccurrenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventOccurrenceRepository extends \Doctrine\ORM\EntityRepository
{
}
