# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    amoussard:
                        password: quantum2016
                        roles: 'ROLE_ADMIN'
                    mlefebvre:
                        password: quantum2016
                        roles: 'ROLE_ADMIN'
                    nrousseau:
                        password: quantum2016
                        roles: 'ROLE_ADMIN'
                    kpilon:
                        password: quantum2016
                        roles: 'ROLE_ADMIN'

    acl:
        connection: default

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/translate, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
