services:
    admin.event_occurrence:
        class: AppBundle\Admin\EventOccurrenceAdmin
        arguments: [~, AppBundle\Entity\EventOccurrence, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: EventOccurrence
    admin.location:
        class: AppBundle\Admin\LocationAdmin
        arguments: [~, AppBundle\Entity\Location, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Location


    admin.conference:
        class: AppBundle\Admin\Events\ConferenceAdmin
        arguments: [~, AppBundle\Entity\Events\Conference, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Conference
    admin.meet_a_coach:
        class: AppBundle\Admin\Events\MeetACoachAdmin
        arguments: [~, AppBundle\Entity\Events\MeetACoach, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Meet a coach
    admin.power_training:
        class: AppBundle\Admin\Events\PowerTrainingAdmin
        arguments: [~, AppBundle\Entity\Events\PowerTraining, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: PowerTraining
    admin.seminar:
        class: AppBundle\Admin\Events\SeminarAdmin
        arguments: [~, AppBundle\Entity\Events\Seminar, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Seminar
    admin.workshop:
        class: AppBundle\Admin\Events\WorkshopAdmin
        arguments: [~, AppBundle\Entity\Events\Workshop, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Workshop
    admin.other:
        class: AppBundle\Admin\Events\OtherAdmin
        arguments: [~, AppBundle\Entity\Events\Other, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Other

    admin.services.services:
        class: AppBundle\Admin\Services\ServiceAdmin
        arguments: [~, AppBundle\Entity\Services\Service, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Coaching
              label: Services
    admin.services.coaching_packages:
        class: AppBundle\Admin\Services\CoachingPackageAdmin
        arguments: [~, AppBundle\Entity\Services\CoachingPackage, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Coaching
              label: Packages

    admin.services.development_packages:
        class: AppBundle\Admin\Services\DevelopmentPackageAdmin
        arguments: [~, AppBundle\Entity\Services\DevelopmentPackage, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Studio
              label: Packages

    admin.services.extra_development_packages:
        class: AppBundle\Admin\Services\ExtraDevelopmentPackageAdmin
        arguments: [~, AppBundle\Entity\Services\ExtraDevelopmentPackage, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Studio
              label: Extras

    admin.person:
        class: AppBundle\Admin\PersonAdmin
        arguments: [~, AppBundle\Entity\Person, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Community Management
              label: People

    admin.certification:
        class: AppBundle\Admin\CertificationAdmin
        arguments: [~, AppBundle\Entity\Certification, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Community Management
              label: Certifications

    admin.testimonials:
        class: AppBundle\Admin\TestimonialAdmin
        arguments: [~, AppBundle\Entity\Testimonial, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Community Management
              label: Testimonial


    admin.event_occurrence_cost:
        class: AppBundle\Admin\EventOccurrenceCostAdmin
        arguments: [~, AppBundle\Entity\EventOccurrenceCost, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: EventOccurrenceCost

    admin.person_translation:
        class: AppBundle\Admin\PersonTranslationAdmin
        arguments: [~, AppBundle\Entity\PersonTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: PersonTranslation

    admin.event_translation:
        class: AppBundle\Admin\EventTranslationAdmin
        arguments: [~, AppBundle\Entity\EventTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: EventTranslation

    admin.event_occurrence_translation:
        class: AppBundle\Admin\EventOccurrenceTranslationAdmin
        arguments: [~, AppBundle\Entity\EventOccurrenceTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: EventOccurrenceTranslation

    admin.service_translation:
        class: AppBundle\Admin\Services\ServiceTranslationAdmin
        arguments: [~, AppBundle\Entity\Services\ServiceTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: ServiceTranslation
    admin.coaching_package_translation:
        class: AppBundle\Admin\Services\CoachingPackageTranslationAdmin
        arguments: [~, AppBundle\Entity\Services\CoachingPackageTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: CoachingPackageTranslation
    admin.development_package_translation:
        class: AppBundle\Admin\Services\DevelopmentPackageTranslationAdmin
        arguments: [~, AppBundle\Entity\Services\DevelopmentPackageTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: DevelopmentPackageTranslation
    admin.extra_development_package_translation:
        class: AppBundle\Admin\Services\ExtraDevelopmentPackageTranslationAdmin
        arguments: [~, AppBundle\Entity\Services\ExtraDevelopmentPackageTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: ExtraDevelopmentPackageTranslation
