services:
    admin.event_occurrence:
        class: AppBundle\Admin\EventOccurrenceAdmin
        arguments: [~, AppBundle\Entity\EventOccurrence, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: EventOccurrence
    admin.location:
        class: AppBundle\Admin\LocationAdmin
        arguments: [~, AppBundle\Entity\Location, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Location


    admin.trainings.workshop:
        class: AppBundle\Admin\Trainings\WorkshopAdmin
        arguments: [~, AppBundle\Entity\Trainings\Workshop, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Trainings
              label: Workshop
    admin.trainings.learning_path:
        class: AppBundle\Admin\Trainings\LearningPathAdmin
        arguments: [~, AppBundle\Entity\Trainings\LearningPath, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Trainings
              label: LearningPath
    admin.trainings.module:
        class: AppBundle\Admin\Trainings\ModuleAdmin
        arguments: [~, AppBundle\Entity\Trainings\Module, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Trainings
              label: Module
    admin.trainings.tag:
        class: AppBundle\Admin\TagAdmin
        arguments: [~, AppBundle\Entity\Tag, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Trainings
              label: Tag


    admin.sessions.workshop_session:
        class: AppBundle\Admin\Sessions\WorkshopSessionAdmin
        arguments: [~, AppBundle\Entity\Sessions\WorkshopSession, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Sessions
              label: Workshop
    admin.sessions.learning_path_session:
        class: AppBundle\Admin\Sessions\LearningPathSessionAdmin
        arguments: [~, AppBundle\Entity\Sessions\LearningPathSession, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Sessions
              label: Learning Path
    admin.sessions.custom_session:
        class: AppBundle\Admin\Sessions\CustomSessionAdmin
        arguments: [~, AppBundle\Entity\Sessions\CustomSession, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Sessions
              label: Custom
    admin.sessions.course:
        class: AppBundle\Admin\Sessions\CourseAdmin
        arguments: [~, AppBundle\Entity\Sessions\Course, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Sessions
              label: Course


    admin.conference:
        class: AppBundle\Admin\Events\ConferenceAdmin
        arguments: [~, AppBundle\Entity\Events\Conference, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Conference
    admin.meet_a_coach:
        class: AppBundle\Admin\Events\MeetACoachAdmin
        arguments: [~, AppBundle\Entity\Events\MeetACoach, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Meet a coach
    admin.power_training:
        class: AppBundle\Admin\Events\PowerTrainingAdmin
        arguments: [~, AppBundle\Entity\Events\PowerTraining, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: PowerTraining
    admin.seminar:
        class: AppBundle\Admin\Events\SeminarAdmin
        arguments: [~, AppBundle\Entity\Events\Seminar, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Seminar
    admin.workshop:
        class: AppBundle\Admin\Events\WorkshopAdmin
        arguments: [~, AppBundle\Entity\Events\Workshop, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Workshop
    admin.other:
        class: AppBundle\Admin\Events\OtherAdmin
        arguments: [~, AppBundle\Entity\Events\Other, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Events
              label: Other

    admin.services:
        class: AppBundle\Admin\Services\ServiceAdmin
        arguments: [~, AppBundle\Entity\Services\Service, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Services
              label: Service
    admin.packages:
        class: AppBundle\Admin\Services\PackageAdmin
        arguments: [~, AppBundle\Entity\Services\Package, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Services
              label: Package

    admin.discounts:
        class: AppBundle\Admin\DiscountAdmin
        arguments: [~, AppBundle\Entity\Discount, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Discounts
              label: Discount

    admin.person:
        class: AppBundle\Admin\PersonAdmin
        arguments: [~, AppBundle\Entity\Person, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Community Management
              label: People

    admin.testimonials:
        class: AppBundle\Admin\TestimonialAdmin
        arguments: [~, AppBundle\Entity\Testimonial, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Community Management
              label: Testimonial

    admin.event_occurrence_cost:
        class: AppBundle\Admin\EventOccurrenceCostAdmin
        arguments: [~, AppBundle\Entity\EventOccurrenceCost, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: EventOccurrenceCost

    admin.person_translation:
        class: AppBundle\Admin\PersonTranslationAdmin
        arguments: [~, AppBundle\Entity\PersonTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: PersonTranslation

    admin.event_translation:
        class: AppBundle\Admin\EventTranslationAdmin
        arguments: [~, AppBundle\Entity\EventTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: EventTranslation

    admin.event_occurrence_translation:
        class: AppBundle\Admin\EventOccurrenceTranslationAdmin
        arguments: [~, AppBundle\Entity\EventOccurrenceTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: EventOccurrenceTranslation

    admin.service_translation:
        class: AppBundle\Admin\Services\ServiceTranslationAdmin
        arguments: [~, AppBundle\Entity\Services\ServiceTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: ServiceTranslation
    admin.package_translation:
        class: AppBundle\Admin\Services\PackageTranslationAdmin
        arguments: [~, AppBundle\Entity\Services\PackageTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: PackageTranslation

    admin.discount_translation:
        class: AppBundle\Admin\DiscountTranslationAdmin
        arguments: [~, AppBundle\Entity\DiscountTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: DiscountTranslation

    admin.training_translation:
        class: AppBundle\Admin\Trainings\TrainingTranslationAdmin
        arguments: [~, AppBundle\Entity\Trainings\TrainingTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: TrainingTranslation
    admin.module_translation:
        class: AppBundle\Admin\Trainings\ModuleTranslationAdmin
        arguments: [~, AppBundle\Entity\Trainings\ModuleTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: ModuleTranslation
    admin.tag_translation:
        class: AppBundle\Admin\TagTranslationAdmin
        arguments: [~, AppBundle\Entity\TagTranslation, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: Don't touch !
              label: TagTranslation
