homepage:
    path: /
    defaults:
        _controller: AppBundle:Home:index

service_list:
    path: /services
    defaults:
        _controller: AppBundle:Service:index

training_list:
    path: /trainings
    defaults:
        _controller: AppBundle:Training:index

event_list:
    path: /events
    defaults:
        _controller: AppBundle:Event:index

event_show:
    path: /events/{id}
    defaults:
        _controller: AppBundle:Event:show

about_us:
    path: /about-us
    defaults:
        _controller: AppBundle:AboutUs:index

blog:
    path: /blog
    defaults:
        _controller: AppBundle:News:archive

blog_view:
    path: /blog/{permalink}.{_format}
    defaults:
        _controller: AppBundle:News:view
        _format: html
    requirements:
        permalink: '.+?'

contact:
    path: /contact
    methods: POST
    defaults:
        _controller: AppBundle:AboutUs:contact
    options: { i18n: false }

newsletter:
    path: /newsletter
    methods: POST
    defaults:
        _controller: AppBundle:AboutUs:newsletter
    options: { i18n: false }
