homepage:
    path: /
    defaults:
        _controller: AppBundle:Home:index

services:
    path: /services
    defaults:
        _controller: AppBundle:Services:index

coaching:
    path: /coaching
    defaults:
        _controller: AppBundle:Services:coaching

academy:
    path: /academy
    defaults:
        _controller: AppBundle:Services:academy

studio:
    path: /studio
    defaults:
        _controller: AppBundle:Services:studio

event_list:
    path: /events
    defaults:
        _controller: AppBundle:Event:index

event_show:
    path: /events/{id}
    defaults:
        _controller: AppBundle:Event:show

about_us:
    path: /about-us
    defaults:
        _controller: AppBundle:AboutUs:index

blog:
    path: /blog
    defaults:
        _controller: AppBundle:News:archive

blog_view:
    path: /blog/{permalink}.{_format}
    defaults:
        _controller: AppBundle:News:view
        _format: html
    requirements:
        permalink: '.+?'

contact:
    path: /contact
    methods: POST
    defaults:
        _controller: AppBundle:AboutUs:contact
    options: { i18n: false }

newsletter:
    path: /newsletter
    methods: GET
    defaults:
        _controller: AppBundle:Newsletter:index

newsletter_submit:
    path: /newsletter/submit
    methods: POST
    defaults:
        _controller: AppBundle:Newsletter:submit
    options: { i18n: false }

campaign:
    path: /{slug}
    defaults:
        _controller: AppBundle:Marketing:index

campaign_success:
    path: /{slug}/success
    defaults:
        _controller: AppBundle:Marketing:success

campaign_contact:
    path: /{slug}/contact
    defaults:
        _controller: AppBundle:Marketing:contact

campaign_contact_success:
    path: /{slug}/contact/success
    defaults:
        _controller: AppBundle:Marketing:contactSuccess
