homepage:
    path: /
    defaults:
        _controller: AppBundle:Home:index

coaching_list:
    path: /coaching
    defaults:
        _controller: AppBundle:Coaching:index

discount_list:
    path: /discounts
    defaults:
        _controller: AppBundle:Discount:index

academy_index:
    path: /academy
    defaults:
        _controller: AppBundle:Academy:index

event_list:
    path: /events
    defaults:
        _controller: AppBundle:Event:index

event_show:
    path: /events/{id}
    defaults:
        _controller: AppBundle:Event:show

about_us:
    path: /about-us
    defaults:
        _controller: AppBundle:AboutUs:index

blog:
    path: /blog
    defaults:
        _controller: AppBundle:News:archive

blog_view:
    path: /blog/{permalink}.{_format}
    defaults:
        _controller: AppBundle:News:view
        _format: html
    requirements:
        permalink: '.+?'

contact:
    path: /contact
    methods: POST
    defaults:
        _controller: AppBundle:AboutUs:contact
    options: { i18n: false }

newsletter:
    path: /newsletter
    methods: GET
    defaults:
        _controller: AppBundle:Newsletter:index

newsletter_submit:
    path: /newsletter/submit
    methods: POST
    defaults:
        _controller: AppBundle:Newsletter:submit
    options: { i18n: false }
