services:
    app.manager.location:
        class: AppBundle\Manager\LocationManager
        arguments:
            - '@doctrine.orm.entity_manager'

    app.manager.search_engine:
        class: AppBundle\Manager\SearchEngine
        arguments:
            - '@doctrine.orm.entity_manager'

    app.manager.breadcrumb_generator:
        class: AppBundle\Manager\BreadcrumbsGenerator
        arguments:
            - '@white_october_breadcrumbs'
            - '@app.twig.object_translator'

    app.twig.object_translator:
        class: AppBundle\Manager\ObjectTranslator
        arguments: ['@request_stack']

    app.manager.newsletter:
        class: AppBundle\Manager\NewsletterManager
        arguments:
          - '@request_stack'
          - '@csa_guzzle.client.mailchimp_api'
          - '%newsletter_list_id%'

    app.twig.locale_extension:
        class: AppBundle\Twig\LocaleExtension
        arguments: [ "@router" ]
        tags:
            - { name: twig.extension }

    app.twig.translate_extension:
        class: AppBundle\Twig\TranslateExtension
        arguments: ["@app.twig.object_translator"]
        tags:
            - { name : twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
