services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - '@knp_menu.factory'
            - '@app.manager.locale_manager'
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } # The alias is what is used to retrieve the menu

    app.manager.location:
        class: AppBundle\Manager\LocationManager
        arguments:
            - '@doctrine.orm.entity_manager'

    app.manager.search_engine:
        class: AppBundle\Manager\SearchEngine
        arguments:
            - '@doctrine.orm.entity_manager'

    app.manager.media_manager:
        class: AppBundle\Manager\MediaManager
        arguments:
            - '@sonata.media.pool'

    app.manager.breadcrumb_generator:
        class: AppBundle\Manager\BreadcrumbsGenerator
        arguments:
            - '@white_october_breadcrumbs'
            - '@app.twig.object_translator'

    app.manager.emails:
        class: AppBundle\Manager\EmailManager
        arguments:
            - '@mailer'
            - '@templating'
            - '%emails.general%'
            - '%emails.admin%'

    app.twig.object_translator:
        class: AppBundle\Manager\ObjectTranslator
        arguments: ['@request_stack']

    app.manager.mailchimp_newsletter:
        class: AppBundle\Manager\MailchimpListManager
        arguments:
          - '@request_stack'
          - '@csa_guzzle.client.mailchimp_api'
          - '@translator'
          - '%newsletter_list_id%'

    app.manager.mailchimp_list:
        class: AppBundle\Manager\MailchimpListManager
        arguments:
          - '@request_stack'
          - '@csa_guzzle.client.mailchimp_api'
          - '@translator'

    app.manager.locale_manager:
        class: AppBundle\Manager\LocaleManager
        arguments:
            - '@router'
            - '@request_stack'

    app.twig.locale_extension:
        class: AppBundle\Twig\LocaleExtension
        arguments:
            - '@app.manager.locale_manager'
        tags:
            - { name : twig.extension }

    app.twig.translate_extension:
        class: AppBundle\Twig\TranslateExtension
        arguments: ["@app.twig.object_translator"]
        tags:
            - { name : twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.listener.metadata_subscriber:
        class:     AppBundle\EventListener\MetadataSubscriber
        arguments:
          - '@request_stack'
          - '@translator'
          - '@router'
          - '@templating.helper.assets'
          - '@sonata.seo.page'
          - '@doctrine.orm.entity_manager'
          - '@app.twig.object_translator'
          - '@app.manager.media_manager'
          - '@sonata.news.manager.post'
          - '@sonata.news.blog'
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    app.sitemap.blog_post_subscriber:
        class:     AppBundle\EventListener\SitemapBlogPostSubscriber
        arguments:
            - "@router"
            - "@sonata.news.manager.post"
            - "@sonata.news.blog"
            - "@app.manager.media_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    app.sitemap.static_pages_subscriber:
        class:     AppBundle\EventListener\SitemapStaticPagesSubscriber
        arguments:
            - "@router"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    app.sitemap.events_subscriber:
        class:     AppBundle\EventListener\SitemapEventsSubscriber
        arguments:
            - "@router"
            - "@app.manager.search_engine"
            - "@app.manager.media_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }
