AppBundle\Entity\Events\Conference:
  conference-{1..2}:
    translations: []

AppBundle\Entity\Events\MeetACoach:
  meet-a-coach-{1..2}:
    translations: []

AppBundle\Entity\Events\PowerTraining:
  power-training-{1..2}:
    translations: []

AppBundle\Entity\Events\Seminar:
  seminar-{1..2}:
    translations: []

AppBundle\Entity\Events\Workshop:
  workshop-{1..2}:
    translations: []

AppBundle\Entity\Events\Other:
  other-{1..2}:
    translations: []

AppBundle\Entity\EventTranslation:
  event-fr (template):
    locale: fr
    name: fr <sentence()>
    description: fr <paragraph(6)>

  event-en (template):
    locale: en
    name: en <sentence()>
    description: en <paragraph(6)>

  conference-fr-{1..2} (extends event-fr):
    event: @conference-<current()>

  conference-en-{1..2} (extends event-en):
    event: @conference-<current()>

  meet-a-coach-fr-{1..2} (extends event-fr):
    event: @meet-a-coach-<current()>

  meet-a-coach-en-{1..2} (extends event-en):
    event: @meet-a-coach-<current()>

  power-training-fr-{1..2} (extends event-fr):
    event: @power-training-<current()>

  power-training-en-{1..2} (extends event-en):
    event: @power-training-<current()>

  seminar-fr-{1..2} (extends event-fr):
    event: @seminar-<current()>

  seminar-en-{1..2} (extends event-en):
    event: @seminar-<current()>

  workshop-fr-{1..2} (extends event-fr):
    event: @workshop-<current()>

  workshop-en-{1..2} (extends event-en):
    event: @workshop-<current()>

  other-fr-{1..2} (extends event-fr):
    event: @other-<current()>

  other-en-{1..2} (extends event-en):
    event: @other-<current()>
