AppBundle\Entity\Coaching\PackageTranslation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Coaching\PackageTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 5
        name:
            type: string
            length: 255
        description:
            type: text
    manyToOne:
        package:
            targetEntity: AppBundle\Entity\Coaching\Package
            inversedBy: translations
            joinColumn:
                nullable: false
                onDelete: cascade
    lifecycleCallbacks: {  }
