AppBundle\Entity\Discount:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DiscountRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        position:
            type: integer
            nullable: true

    manyToOne:
        picture:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"

    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\DiscountTranslation
            mappedBy: discount
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"
            indexBy: locale

    lifecycleCallbacks: {  }
