AppBundle\Entity\EventTranslation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EventTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 5
        name:
            type: string
            length: 255
        intro:
            type: text
            nullable: true
        description:
            type: text

    manyToOne:
        event:
            targetEntity: AppBundle\Entity\Event
            inversedBy: translations
            cascade:
            joinColumn:
                nullable: false
                onDelete: cascade
    lifecycleCallbacks: {  }
