AppBundle\Entity\EventOccurrenceTranslation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EventOccurrenceTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 5
        name:
            type: string
            length: 255
        description:
            type: text

    manyToOne:
        eventOccurrence:
            targetEntity: AppBundle\Entity\EventOccurrence
            inversedBy: translations
            joinColumn:
                nullable: false
                onDelete: cascade
    lifecycleCallbacks: {  }
