AppBundle\Entity\EventOccurrence:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EventOccurrenceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        begin:
            type: datetime
        end:
            type: datetime
        remainingSeats:
            type: integer
        eventBriteLink:
            type: string
            length: 255
            nullable: true
        free:
            type: boolean
        languages:
            type: simple_array
            nullable: true
    manyToOne:
        event:
            targetEntity: AppBundle\Entity\Event
        location:
            targetEntity: AppBundle\Entity\Location
            fetch: EAGER
        picture:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"
    oneToMany:
        costs:
            targetEntity: AppBundle\Entity\EventOccurrenceCost
            mappedBy: eventOccurrence
            cascade:
                - "persist"
                - "remove"
        translations:
            targetEntity: AppBundle\Entity\EventOccurrenceTranslation
            mappedBy: eventOccurrence
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"
            indexBy: locale
    manyToMany:
        speakers:
            targetEntity: AppBundle\Entity\Person
            joinTable:
                name: event_occurences_speakers
                joinColumns:
                    event_occurence_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    speaker_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
