AppBundle\Entity\LandingPageTranslation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LandingPageTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 5
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 128
            gedmo:
                slug:
                    fields:
                        - title
        intro:
            type: text
        submitButtonLabel:
            type: string
            length: 255
        successMessage:
            type: string
            length: 255
        formTitle:
            type: string
            length: 255
        mailChimpListId:
            type: string
            length: 255

    manyToOne:
        picture:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"

        landingPage:
            targetEntity: AppBundle\Entity\LandingPage
            inversedBy: translations
            joinColumn:
                nullable: false
                onDelete: cascade

    oneToMany:
        contacts:
            targetEntity: AppBundle\Entity\LandingPageContact
            mappedBy: landingPageTranslation
            cascade:
                - "persist"
            indexBy: locale

    lifecycleCallbacks: {  }
