AppBundle\Entity\Services\Service:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Services\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        position:
            type: integer
            nullable: true
        price:
            type: decimal
            precision: 10
            scale: 2
            nullable: true

    manyToOne:
        picture:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"

    oneToMany:
        packages:
            targetEntity: AppBundle\Entity\Services\Package
            mappedBy: service

        translations:
            targetEntity: AppBundle\Entity\Services\ServiceTranslation
            mappedBy: service
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"
            indexBy: locale

    lifecycleCallbacks: {  }
