AppBundle\Entity\Service:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ServiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        picture:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\ServiceTranslation
            mappedBy: service
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"
            indexBy: locale
    lifecycleCallbacks: {  }
