AppBundle\Entity\ServiceTranslation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ServiceTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 5
        name:
            type: string
            length: 255
        description:
            type: text
        specifications:
            type: text
    manyToOne:
        service:
            targetEntity: AppBundle\Entity\Service
            inversedBy: translations
            joinColumn:
                nullable: false
                onDelete: cascade
    lifecycleCallbacks: {  }
