AppBundle\Entity\Sessions\Session:
    type: entity
    table: null
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
        length: 255
    discriminatorMap:
        workshop: AppBundle\Entity\Sessions\WorkshopSession
        learning_path: AppBundle\Entity\Sessions\LearningPathSession
        custom: AppBundle\Entity\Sessions\CustomSession
    repositoryClass: AppBundle\Repository\Sessions\SessionRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        language:
            type: string
            length: 255

    manyToMany:
        courses:
          targetEntity: AppBundle\Entity\Sessions\Course
          fetch: EAGER
          cascade:
              - "persist"
              - "remove"
          joinTable:
            name: session_course
            joinColumns:
              session_id:
                referencedColumnName: id
            inverseJoinColumns:
              course_id:
                referencedColumnName: id

    lifecycleCallbacks: {  }
