AppBundle\Entity\Sessions\LearningPathSession:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Sessions\LearningPathSessionRepository

    manyToOne:
        learningPath:
            targetEntity: AppBundle\Entity\Trainings\LearningPath
            inversedBy: sessions
            joinColumn:
                onDelete: cascade

    lifecycleCallbacks: {  }
