AppBundle\Entity\TagTranslation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TagTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 5
        name:
            type: string
            length: 255

    manyToOne:
        tag:
            targetEntity: AppBundle\Entity\Tag
            inversedBy: translations
            cascade:
                - "persist"
                - "remove"
            joinColumn:
                nullable: false
                onDelete: cascade

    lifecycleCallbacks: {  }
