AppBundle\Entity\Trainings\ModuleTranslation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ModuleTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        locale:
            type: string
            length: 5
        name:
            type: string
            length: 255
        description:
            type: text
    manyToOne:
        module:
            targetEntity: AppBundle\Entity\Trainings\Module
            inversedBy: translations
            joinColumn:
                nullable: false
                onDelete: cascade
    lifecycleCallbacks: {  }
