AppBundle\Entity\Trainings\Module:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\Trainings\ModuleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        learningPath:
            targetEntity: AppBundle\Entity\Trainings\LearningPath
            inversedBy: modules
            cascade:
                - "persist"
                - "remove"
            joinColumn:
                nullable: false
                onDelete: cascade

    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Trainings\ModuleTranslation
            mappedBy: module
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"
            indexBy: locale

    lifecycleCallbacks: {  }
