AppBundle\Entity\Trainings\Training:
    type: entity
    table: null
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
        length: 255
    discriminatorMap:
        workshop: AppBundle\Entity\Trainings\Workshop
        learning_path: AppBundle\Entity\Trainings\LearningPath
    repositoryClass: AppBundle\Repository\TrainingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        position:
            type: integer
            nullable: true
        cost:
            type: decimal
            precision: 10
            scale: 2

    manyToOne:
        picture:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"

    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Trainings\TrainingTranslation
            mappedBy: training
            fetch: EAGER
            cascade:
                - "persist"
                - "remove"
            indexBy: locale

    manyToMany:
        tags:
          targetEntity: AppBundle\Entity\Tag
          fetch: EAGER
          joinTable:
            name: training_tag
            joinColumns:
              training_id:
                referencedColumnName: id
            inverseJoinColumns:
              tag_id:
                referencedColumnName: id

    lifecycleCallbacks: {  }
